### ISSUE TITLE
Windows: mkl and utils package are installed, but are not found by qqp_BaselineModels.py und utils.py

### ISSUE THREAD

**Issue by sanenr9** [ianlokh/Duplicate_Questions#1]
I'm quite new to Python and Tensorflow.
I downloaded your code and installed all dependencies with pip but somehow cannot get your code to run:

I tried with Python 3.6 and 3.5 and although mkl is installed qqp_BaselineModels.py is also complaining:

```
File "K:\path\to\my\project\qqp_BaselineModels.py", line 31, in <module> import utils as utils
File "K:\path\to\my\project\utils.py", line 11, in <module> import mkl
ModuleNotFoundError: No module named 'mkl'
```

pip is saying:

```
Requirement already satisfied: mkl in c:\users\my_user\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: intel-openmp==2018.0.0 in c:\users\my_user\appdata\local\programs\python\python36\lib\site-packages (from mkl)
```

I also already downloaded numpy+MKL from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy but without success.

I also tried using mkl from numpy in your utils.py:

from numpy._distributor_init import NUMPY_MKL 

So somehow i'm stuck here.
Any ideas what i might be doing wrong?

Thanks,

Michael

**Comment by ianlokh** [comment]
Hi Michael,

Try using a lower version of MKL. Are you using Anaconda? If so I recall that there was an issue with some of the later versions of MKL.

If you are using Anaconda, I suggest you download MKL from the Anaconda Navigator package manager - it should automatically recommend the correct version of numpy that works with the MKL version you use (and vice versa).

If you are not using Anaconda, I would recommend that you use it as it helps to ensure that the package dependencies are managed properly.

Let me know if you are still having issues 

Regards 
Ian

**Comment by ianlokh** [comment]
Hi Michael,

I am using MLK 2017.0.3 on Anaconda 3.0

Ian

**Comment by sanenr9** [comment]
Thanks, that helped  :+1:
